<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkFlowSystem.Domain\WorkFlowSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Request\" />
    <Folder Include="InterFaces\" />
  </ItemGroup>

</Project>
